### PR TITLE
Updated packages

### PR DESCRIPTION
**Pull request by khrystuk**

### CODE REVIEW

**Comment by joshterrill** [comment]
@khrystuk Could you combine the two PR's you did into one?

**Comment by khrystuk** [comment]
@joshterrill First PR is not mine

**Comment by joshterrill** [comment]
Sorry, I was reading this through email and didn't realize. Does this PR fix all the vulnerable dependencies?

**Comment by khrystuk** [comment]
@joshterrill npm audit shows 0 vulnerabilities

image

**Comment by joshterrill** [comment]
`npm audit` only looks at `package.json` doesn't it? Because when I run `npm audit` (without your PR), I also show 0 vulnerabilities. But github says the versions that are bad area in the `package-lock.json` file.

screen shot 2018-10-05 at 12 35 00 am

**Comment by khrystuk** [comment]
npm audit before PR. All vulnerabilities should be fixed. 

image

**Comment by joshterrill** [comment]
That's really weird, this is what I see in my terminal:

screen shot 2018-10-05 at 12 50 33 am

Have you ever seen something like that? I'm going to pull your PR down and re-install the deps to make sure everything is still good. Then I'll merge.

**Pull request merged**
